### ISSUE TITLE
Attach html document along with email bot message.

### ISSUE THREAD

**Issue by allenbrubaker** [3846masa/smtp2slack#1]
I love this docker image! I just tested it and it is working very nicely.  One feature I would like to request is if it is possible to attach the actual html body, so I can debug the styling of the original email when running the html in the browser.  Thank you!

**Comment by 3846masa** [comment]
This script use [Flolagale/mailin], `msg` is mailin's Message Object (See [here][mailin-webhook])

[Flolagale/mailin]: https://github.com/Flolagale/mailin
[mailin-webhook]: https://github.com/Flolagale/mailin#webhook-format

If you want to receive html instead of text, please fork and rewrite https://github.com/3846masa/smtp2slack/blob/773d7ffa6ece749c256f934648b0aa02b7a168e4/index.js#L35-L44 likes below.

```js
text: msg.html
```
